// <auto-generated />
using System;
using CrashReport.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrashReport.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260626122446_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CrashReport.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Station")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CrashReport.Models.ContributoryFactor", b =>
                {
                    b.Property<int>("FactorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("factor_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FactorId"));

                    b.Property<int>("CrashId")
                        .HasColumnType("int")
                        .HasColumnName("crash_id");

                    b.Property<string>("FactorCategory")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("factor_category");

                    b.Property<string>("FactorDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("factor_description");

                    b.Property<bool>("IsMajorFactor")
                        .HasColumnType("bit")
                        .HasColumnName("is_major_factor");

                    b.HasKey("FactorId");

                    b.HasIndex("CrashId")
                        .HasDatabaseName("idx_cf_crash");

                    b.HasIndex("FactorCategory")
                        .HasDatabaseName("idx_cf_category");

                    b.ToTable("contributory_factors", (string)null);
                });

            modelBuilder.Entity("CrashReport.Models.Crash", b =>
                {
                    b.Property<int>("CrashId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("crash_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrashId"));

                    b.Property<string>("BriefDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("brief_description");

                    b.Property<string>("CapturingNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("capturing_number");

                    b.Property<string>("CasNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("cas_no");

                    b.Property<string>("CrNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("cr_no");

                    b.Property<DateOnly>("CrashDate")
                        .HasColumnType("date")
                        .HasColumnName("crash_date");

                    b.Property<TimeOnly?>("CrashTime")
                        .HasColumnType("time")
                        .HasColumnName("crash_time");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("IncidentReportNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("incident_report_no");

                    b.Property<string>("KmMarker")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("km_marker");

                    b.Property<byte?>("NoOfAppendices")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("no_of_appendices");

                    b.Property<byte?>("NoOfVehiclesInvolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("no_of_vehicles_involved");

                    b.Property<string>("ProvinceCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("province_code");

                    b.Property<string>("RoadNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("road_number");

                    b.Property<short?>("SpeedLimitKmh")
                        .HasColumnType("smallint")
                        .HasColumnName("speed_limit_kmh");

                    b.Property<string>("VehicleString")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CrashId");

                    b.HasIndex("CasNo")
                        .HasDatabaseName("idx_crashes_cas_no");

                    b.HasIndex("CrashDate")
                        .HasDatabaseName("idx_crashes_date");

                    b.HasIndex("ProvinceCode")
                        .HasDatabaseName("idx_crashes_province");

                    b.ToTable("crashes", (string)null);
                });

            modelBuilder.Entity("CrashReport.Models.CrashCondition", b =>
                {
                    b.Property<int>("ConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("condition_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConditionId"));

                    b.Property<int>("CrashId")
                        .HasColumnType("int")
                        .HasColumnName("crash_id");

                    b.Property<string>("CrashType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("crash_type");

                    b.Property<bool?>("HitAndRun")
                        .HasColumnType("bit")
                        .HasColumnName("hit_and_run");

                    b.Property<string>("LightCondition")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("light_condition");

                    b.Property<string>("ObstructionType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("obstruction_type");

                    b.Property<string>("OtherObservations")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("other_observations");

                    b.Property<string>("OvertakingControl")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("overtaking_control");

                    b.Property<string>("RoadMarkingVisibility")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("road_marking_visibility");

                    b.Property<string>("RoadSegmentGrade")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("road_segment_grade");

                    b.Property<string>("RoadSignsCondition")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("road_signs_condition");

                    b.Property<string>("TrafficControlType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("traffic_control_type");

                    b.Property<string>("TyreBurstObserved")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tyre_burst_observed");

                    b.Property<string>("VehicleLightsCondition")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("vehicle_lights_condition");

                    b.HasKey("ConditionId");

                    b.HasIndex("CrashId");

                    b.ToTable("crash_conditions", (string)null);
                });

            modelBuilder.Entity("CrashReport.Models.CrashDemographicRecord", b =>
                {
                    b.Property<int>("DemoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("demo_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DemoId"));

                    b.Property<int>("Age0to7")
                        .HasColumnType("int")
                        .HasColumnName("age_0_7");

                    b.Property<int>("Age13to18")
                        .HasColumnType("int")
                        .HasColumnName("age_13_18");

                    b.Property<int>("Age19to35")
                        .HasColumnType("int")
                        .HasColumnName("age_19_35");

                    b.Property<int>("Age36Plus")
                        .HasColumnType("int")
                        .HasColumnName("age_36_plus");

                    b.Property<int>("Age8to12")
                        .HasColumnType("int")
                        .HasColumnName("age_8_12");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CyclistFemale")
                        .HasColumnType("int")
                        .HasColumnName("cyclist_female");

                    b.Property<int>("CyclistMale")
                        .HasColumnType("int")
                        .HasColumnName("cyclist_male");

                    b.Property<int>("DriverFemale")
                        .HasColumnType("int")
                        .HasColumnName("driver_female");

                    b.Property<int>("DriverMale")
                        .HasColumnType("int")
                        .HasColumnName("driver_male");

                    b.Property<int>("PassengerFemale")
                        .HasColumnType("int")
                        .HasColumnName("passenger_female");

                    b.Property<int>("PassengerMale")
                        .HasColumnType("int")
                        .HasColumnName("passenger_male");

                    b.Property<int>("PedestrianFemale")
                        .HasColumnType("int")
                        .HasColumnName("pedestrian_female");

                    b.Property<int>("PedestrianMale")
                        .HasColumnType("int")
                        .HasColumnName("pedestrian_male");

                    b.Property<DateOnly>("PeriodFrom")
                        .HasColumnType("date")
                        .HasColumnName("period_from");

                    b.Property<DateOnly>("PeriodTo")
                        .HasColumnType("date")
                        .HasColumnName("period_to");

                    b.Property<string>("ProvinceCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("province_code");

                    b.Property<int>("RaceBlack")
                        .HasColumnType("int")
                        .HasColumnName("race_black");

                    b.Property<int>("RaceColoured")
                        .HasColumnType("int")
                        .HasColumnName("race_coloured");

                    b.Property<int>("RaceIndian")
                        .HasColumnType("int")
                        .HasColumnName("race_indian");

                    b.Property<int>("RaceOther")
                        .HasColumnType("int")
                        .HasColumnName("race_other");

                    b.Property<int>("RaceWhite")
                        .HasColumnType("int")
                        .HasColumnName("race_white");

                    b.HasKey("DemoId");

                    b.ToTable("crash_demographics");
                });

            modelBuilder.Entity("CrashReport.Models.CrashLocation", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("AreaType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("area_type");

                    b.Property<string>("BetweenFrom")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("between_from");

                    b.Property<string>("BetweenTo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("between_to");

                    b.Property<bool?>("BuiltUpArea")
                        .HasColumnType("bit")
                        .HasColumnName("built_up_area");

                    b.Property<string>("CityTown")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city_town");

                    b.Property<string>("CompassDirection")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("compass_direction");

                    b.Property<int>("CrashId")
                        .HasColumnType("int")
                        .HasColumnName("crash_id");

                    b.Property<decimal?>("DistanceKm")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("distance_km");

                    b.Property<string>("FromPoint")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("from_point");

                    b.Property<decimal?>("GpsXCoordinate")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("gps_x_coordinate");

                    b.Property<decimal?>("GpsYCoordinate")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("gps_y_coordinate");

                    b.Property<string>("IntersectionRoadNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("intersection_road_no");

                    b.Property<string>("IntersectionStreet")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("intersection_street");

                    b.Property<string>("JunctionType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("junction_type");

                    b.Property<string>("KmMarkerInfo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("km_marker_info");

                    b.Property<string>("NextCityTown")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("next_city_town");

                    b.Property<string>("RoadFunctionalClassification")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("road_functional_classification");

                    b.Property<string>("RoadLayout")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("road_layout");

                    b.Property<string>("RoadSurfaceCondition")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("road_surface_condition");

                    b.Property<string>("RoadSurfaceQuality")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("road_surface_quality");

                    b.Property<string>("RoadSurfaceType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("road_surface_type");

                    b.Property<string>("StreetRoadName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("street_road_name");

                    b.Property<string>("Suburb")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("suburb");

                    b.HasKey("LocationId");

                    b.HasIndex("CrashId");

                    b.ToTable("crash_locations", (string)null);
                });

            modelBuilder.Entity("CrashReport.Models.CrashPerson", b =>
                {
                    b.Property<int>("CrashPersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("crash_person_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrashPersonId"));

                    b.Property<string>("AmbulanceServiceRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ambulance_service_ref");

                    b.Property<string>("ChildRestraintUsed")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("child_restraint_used");

                    b.Property<int>("CrashId")
                        .HasColumnType("int")
                        .HasColumnName("crash_id");

                    b.Property<int?>("CrashVehicleId")
                        .HasColumnType("int")
                        .HasColumnName("crash_vehicle_id");

                    b.Property<string>("Hospital")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("hospital");

                    b.Property<string>("LiquorDrugSuspected")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("liquor_drug_suspected");

                    b.Property<string>("LiquorDrugTestDone")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("liquor_drug_test_done");

                    b.Property<byte?>("PassengerNumber")
                        .HasColumnType("tinyint")
                        .HasColumnName("passenger_number");

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("person_id");

                    b.Property<string>("PersonReference")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("person_reference");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("SeatbeltHelmetUsed")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("seatbelt_helmet_used");

                    b.Property<string>("SeatingPosition")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("seating_position");

                    b.Property<string>("SeverityOfInjury")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("severity_of_injury");

                    b.Property<string>("VehicleReference")
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("vehicle_reference")
                        .IsFixedLength();

                    b.HasKey("CrashPersonId");

                    b.HasIndex("CrashId")
                        .HasDatabaseName("idx_cp_crash");

                    b.HasIndex("CrashVehicleId");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("idx_cp_person");

                    b.HasIndex("SeverityOfInjury")
                        .HasDatabaseName("idx_cp_injury");

                    b.ToTable("crash_persons", (string)null);
                });

            modelBuilder.Entity("CrashReport.Models.CrashSketch", b =>
                {
                    b.Property<int>("SketchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sketch_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SketchId"));

                    b.Property<int>("CrashId")
                        .HasColumnType("int")
                        .HasColumnName("crash_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_path");

                    b.Property<string>("NorthDirection")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("north_direction");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("SketchType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("accident")
                        .HasColumnName("sketch_type");

                    b.HasKey("SketchId");

                    b.HasIndex("CrashId");

                    b.ToTable("crash_sketches", (string)null);
                });

            modelBuilder.Entity("CrashReport.Models.CrashVehicle", b =>
                {
                    b.Property<int>("CrashVehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("crash_vehicle_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrashVehicleId"));

                    b.Property<string>("AlcoholSuspected")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("alcohol_suspected");

                    b.Property<string>("AlcoholTestResult")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("alcohol_test_result");

                    b.Property<string>("BreakdownCompany")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("breakdown_company");

                    b.Property<int>("CrashId")
                        .HasColumnType("int")
                        .HasColumnName("crash_id");

                    b.Property<int?>("DriverPersonId")
                        .HasColumnType("int")
                        .HasColumnName("driver_person_id");

                    b.Property<string>("DrugSuspected")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("drug_suspected");

                    b.Property<string>("DrugTestResult")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("drug_test_result");

                    b.Property<string>("PassengersForReward")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("passengers_for_reward");

                    b.Property<string>("PositionBeforeCrash")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("position_before_crash");

                    b.Property<string>("SeatbeltUsed")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("seatbelt_used");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("VehicleManoeuvre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vehicle_manoeuvre");

                    b.Property<string>("VehicleReference")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("vehicle_reference")
                        .IsFixedLength();

                    b.Property<string>("VehicleType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vehicle_type");

                    b.HasKey("CrashVehicleId");

                    b.HasIndex("CrashId")
                        .HasDatabaseName("idx_cv_crash");

                    b.HasIndex("DriverPersonId")
                        .HasDatabaseName("idx_cv_driver");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("idx_cv_vehicle");

                    b.ToTable("crash_vehicles", (string)null);
                });

            modelBuilder.Entity("CrashReport.Models.CrashWeather", b =>
                {
                    b.Property<int>("CrashId")
                        .HasColumnType("int")
                        .HasColumnName("crash_id");

                    b.Property<string>("WeatherCondition")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("weather_condition");

                    b.HasKey("CrashId", "WeatherCondition");

                    b.ToTable("crash_weather", (string)null);
                });

            modelBuilder.Entity("CrashReport.Models.DangerousGood", b =>
                {
                    b.Property<int>("DgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("dg_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DgId"));

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("company_name");

                    b.Property<int>("CrashId")
                        .HasColumnType("int")
                        .HasColumnName("crash_id");

                    b.Property<string>("EmergencyServicesActivated")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("emergency_services_activated");

                    b.Property<string>("GoodsCarried")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("goods_carried");

                    b.Property<string>("PlacardDisplayed")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("placard_displayed");

                    b.Property<string>("SpillageObserved")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("spillage_observed");

                    b.Property<string>("UnNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("un_number");

                    b.Property<string>("VapourGasEmission")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("vapour_gas_emission");

                    b.Property<string>("VehicleReference")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("vehicle_reference")
                        .IsFixedLength();

                    b.HasKey("DgId");

                    b.HasIndex("CrashId");

                    b.ToTable("dangerous_goods", (string)null);
                });

            modelBuilder.Entity("CrashReport.Models.DriversLicence", b =>
                {
                    b.Property<int>("LicenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("licence_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LicenceId"));

                    b.Property<DateOnly?>("DateOfIssue")
                        .HasColumnType("date")
                        .HasColumnName("date_of_issue");

                    b.Property<string>("LicenceCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("licence_code");

                    b.Property<string>("LicenceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("licence_number");

                    b.Property<string>("LicenceType")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("licence_type");

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("person_id");

                    b.Property<string>("PrdpCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("prdp_code");

                    b.HasKey("LicenceId");

                    b.HasIndex("PersonId");

                    b.ToTable("drivers_licences", (string)null);
                });

            modelBuilder.Entity("CrashReport.Models.LookupCrashType", b =>
                {
                    b.Property<int>("CrashTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("crash_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrashTypeId"));

                    b.Property<string>("CrashTypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("crash_type_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.HasKey("CrashTypeId");

                    b.ToTable("lkp_crash_types", (string)null);
                });

            modelBuilder.Entity("CrashReport.Models.LookupLocation", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("location_name");

                    b.Property<string>("ProvinceCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("province_code");

                    b.Property<int?>("StationId")
                        .HasColumnType("int")
                        .HasColumnName("station_id");

                    b.HasKey("LocationId");

                    b.HasIndex("StationId");

                    b.ToTable("lkp_locations", (string)null);
                });

            modelBuilder.Entity("CrashReport.Models.LookupRoute", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("route_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("ProvinceCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("province_code");

                    b.Property<string>("RouteCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("route_code");

                    b.HasKey("RouteId");

                    b.ToTable("lkp_routes", (string)null);
                });

            modelBuilder.Entity("CrashReport.Models.LookupVehicleType", b =>
                {
                    b.Property<int>("VehicleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vehicle_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("VehicleTypeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("vehicle_type_code");

                    b.HasKey("VehicleTypeId");

                    b.ToTable("lkp_vehicle_types", (string)null);
                });

            modelBuilder.Entity("CrashReport.Models.OfficialUse", b =>
                {
                    b.Property<int>("OfficialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("official_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfficialId"));

                    b.Property<string>("AccidentRegisterNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("accident_register_no");

                    b.Property<string>("CapturingNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("capturing_number");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comments");

                    b.Property<string>("CompletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("completed_by");

                    b.Property<DateOnly?>("CompletedDate")
                        .HasColumnType("date")
                        .HasColumnName("completed_date");

                    b.Property<string>("CompletedInitials")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("completed_initials");

                    b.Property<string>("CompletedRank")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("completed_rank");

                    b.Property<string>("CompletedServiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("completed_service_number");

                    b.Property<string>("CompletedSignature")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("completed_signature");

                    b.Property<string>("CompletedSurname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("completed_surname");

                    b.Property<TimeOnly?>("CompletedTime")
                        .HasColumnType("time")
                        .HasColumnName("completed_time");

                    b.Property<int>("CrashId")
                        .HasColumnType("int")
                        .HasColumnName("crash_id");

                    b.Property<DateOnly?>("DateStamp")
                        .HasColumnType("date")
                        .HasColumnName("date_stamp");

                    b.Property<string>("DepartmentNameOccurred")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("department_name_occurred");

                    b.Property<string>("DepartmentNameReported")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("department_name_reported");

                    b.Property<string>("InspectedByInitials")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("inspected_by_initials");

                    b.Property<string>("InspectedByRank")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("inspected_by_rank");

                    b.Property<string>("InspectedByServiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("inspected_by_service_number");

                    b.Property<string>("InspectedBySignature")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("inspected_by_signature");

                    b.Property<string>("InspectedBySurname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("inspected_by_surname");

                    b.Property<string>("OccurrenceBookNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("occurrence_book_no");

                    b.Property<string>("OfficeWhereOccurred")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("office_where_occurred");

                    b.Property<string>("OfficeWhereReported")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("office_where_reported");

                    b.Property<string>("SapsCasNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("saps_cas_no");

                    b.HasKey("OfficialId");

                    b.HasIndex("CrashId");

                    b.ToTable("official_use", (string)null);
                });

            modelBuilder.Entity("CrashReport.Models.PedestrianBicyclistDetail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<string>("ClothingColour")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("clothing_colour");

                    b.Property<int>("CrashPersonId")
                        .HasColumnType("int")
                        .HasColumnName("crash_person_id");

                    b.Property<string>("LocationReCrossing")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("location_re_crossing");

                    b.Property<string>("Manoeuvre")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("manoeuvre");

                    b.Property<string>("PedestrianAction")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("pedestrian_action");

                    b.Property<string>("PositionOnRoad")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("position_on_road");

                    b.HasKey("DetailId");

                    b.HasIndex("CrashPersonId");

                    b.ToTable("pedestrian_bicyclist_details", (string)null);
                });

            modelBuilder.Entity("CrashReport.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("person_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<byte?>("Age")
                        .HasColumnType("tinyint")
                        .HasColumnName("age");

                    b.Property<string>("CellPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cell_phone");

                    b.Property<string>("CountryOfOrigin")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("country_of_origin");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FullNames")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("full_names");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gender");

                    b.Property<string>("HomeAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("home_address");

                    b.Property<string>("IdNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("id_number");

                    b.Property<string>("IdType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("id_type");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nationality");

                    b.Property<string>("OtherPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("other_phone");

                    b.Property<string>("PopulationGroup")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("population_group");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("surname");

                    b.Property<string>("WorkContactAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("work_contact_address");

                    b.HasKey("PersonId");

                    b.HasIndex("IdNumber")
                        .HasDatabaseName("idx_persons_id_number");

                    b.HasIndex("Surname")
                        .HasDatabaseName("idx_persons_surname");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("CrashReport.Models.SapsStation", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("station_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("district");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("ProvinceCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("province_code");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("station_name");

                    b.HasKey("StationId");

                    b.ToTable("lkp_saps_stations", (string)null);
                });

            modelBuilder.Entity("CrashReport.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Colour")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("colour");

                    b.Property<string>("CountryOfRegistration")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("RSA")
                        .HasColumnName("country_of_registration");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("LicenceDiscNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("licence_disc_number");

                    b.Property<string>("LicenceTypeFitting")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("licence_type_fitting");

                    b.Property<string>("Make")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("model");

                    b.Property<string>("PrivateOrBusiness")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("private_or_business");

                    b.Property<string>("SpecialFunction")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("special_function");

                    b.Property<string>("TrailerLicenceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trailer_licence_number");

                    b.Property<string>("VehicleCategory")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("vehicle_category");

                    b.Property<string>("VehicleType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleTypeCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("vehicle_type_code");

                    b.Property<string>("VinNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vin_number");

                    b.HasKey("VehicleId");

                    b.HasIndex("LicenceDiscNumber")
                        .HasDatabaseName("idx_vehicles_disc");

                    b.HasIndex("VinNumber")
                        .HasDatabaseName("idx_vehicles_vin");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("CrashReport.Models.VehicleDamage", b =>
                {
                    b.Property<int>("DamageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("damage_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DamageId"));

                    b.Property<int>("CrashVehicleId")
                        .HasColumnType("int")
                        .HasColumnName("crash_vehicle_id");

                    b.Property<string>("DamagePoint")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("damage_point");

                    b.HasKey("DamageId");

                    b.HasIndex("CrashVehicleId");

                    b.ToTable("vehicle_damage", (string)null);
                });

            modelBuilder.Entity("CrashReport.Models.Witness", b =>
                {
                    b.Property<int>("WitnessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("witness_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WitnessId"));

                    b.Property<string>("CellPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cell_phone");

                    b.Property<int>("CrashId")
                        .HasColumnType("int")
                        .HasColumnName("crash_id");

                    b.Property<string>("IdNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("id_number");

                    b.Property<string>("IdType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("id_type");

                    b.Property<string>("OtherPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("other_phone");

                    b.Property<string>("SurnameInitials")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("surname_initials");

                    b.Property<string>("WorkContactAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("work_contact_address");

                    b.HasKey("WitnessId");

                    b.HasIndex("CrashId");

                    b.ToTable("witnesses", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CrashReport.Models.ContributoryFactor", b =>
                {
                    b.HasOne("CrashReport.Models.Crash", "Crash")
                        .WithMany("ContributoryFactors")
                        .HasForeignKey("CrashId")
                        .IsRequired()
                        .HasConstraintName("fk_cf_crash");

                    b.Navigation("Crash");
                });

            modelBuilder.Entity("CrashReport.Models.CrashCondition", b =>
                {
                    b.HasOne("CrashReport.Models.Crash", "Crash")
                        .WithMany("CrashConditions")
                        .HasForeignKey("CrashId")
                        .IsRequired()
                        .HasConstraintName("fk_cc_crash");

                    b.Navigation("Crash");
                });

            modelBuilder.Entity("CrashReport.Models.CrashLocation", b =>
                {
                    b.HasOne("CrashReport.Models.Crash", "Crash")
                        .WithMany("CrashLocations")
                        .HasForeignKey("CrashId")
                        .IsRequired()
                        .HasConstraintName("fk_cl_crash");

                    b.Navigation("Crash");
                });

            modelBuilder.Entity("CrashReport.Models.CrashPerson", b =>
                {
                    b.HasOne("CrashReport.Models.Crash", "Crash")
                        .WithMany("CrashPeople")
                        .HasForeignKey("CrashId")
                        .IsRequired()
                        .HasConstraintName("fk_cp_crash");

                    b.HasOne("CrashReport.Models.CrashVehicle", "CrashVehicle")
                        .WithMany("CrashPeople")
                        .HasForeignKey("CrashVehicleId")
                        .HasConstraintName("fk_cp_crash_vehicle");

                    b.HasOne("CrashReport.Models.Person", "Person")
                        .WithMany("CrashPeople")
                        .HasForeignKey("PersonId")
                        .IsRequired()
                        .HasConstraintName("fk_cp_person");

                    b.Navigation("Crash");

                    b.Navigation("CrashVehicle");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CrashReport.Models.CrashSketch", b =>
                {
                    b.HasOne("CrashReport.Models.Crash", "Crash")
                        .WithMany("CrashSketches")
                        .HasForeignKey("CrashId")
                        .IsRequired()
                        .HasConstraintName("fk_cs_crash");

                    b.Navigation("Crash");
                });

            modelBuilder.Entity("CrashReport.Models.CrashVehicle", b =>
                {
                    b.HasOne("CrashReport.Models.Crash", "Crash")
                        .WithMany("CrashVehicles")
                        .HasForeignKey("CrashId")
                        .IsRequired()
                        .HasConstraintName("fk_cv_crash");

                    b.HasOne("CrashReport.Models.Person", "DriverPerson")
                        .WithMany("CrashVehicles")
                        .HasForeignKey("DriverPersonId")
                        .HasConstraintName("fk_cv_driver");

                    b.HasOne("CrashReport.Models.Vehicle", "Vehicle")
                        .WithMany("CrashVehicles")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("fk_cv_vehicle");

                    b.Navigation("Crash");

                    b.Navigation("DriverPerson");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CrashReport.Models.CrashWeather", b =>
                {
                    b.HasOne("CrashReport.Models.Crash", "Crash")
                        .WithMany("CrashWeathers")
                        .HasForeignKey("CrashId")
                        .IsRequired()
                        .HasConstraintName("fk_cw_crash");

                    b.Navigation("Crash");
                });

            modelBuilder.Entity("CrashReport.Models.DangerousGood", b =>
                {
                    b.HasOne("CrashReport.Models.Crash", "Crash")
                        .WithMany("DangerousGoods")
                        .HasForeignKey("CrashId")
                        .IsRequired()
                        .HasConstraintName("fk_dg_crash");

                    b.Navigation("Crash");
                });

            modelBuilder.Entity("CrashReport.Models.DriversLicence", b =>
                {
                    b.HasOne("CrashReport.Models.Person", "Person")
                        .WithMany("DriversLicences")
                        .HasForeignKey("PersonId")
                        .IsRequired()
                        .HasConstraintName("fk_dl_person");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CrashReport.Models.LookupLocation", b =>
                {
                    b.HasOne("CrashReport.Models.SapsStation", "Station")
                        .WithMany()
                        .HasForeignKey("StationId");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("CrashReport.Models.OfficialUse", b =>
                {
                    b.HasOne("CrashReport.Models.Crash", "Crash")
                        .WithMany("OfficialUses")
                        .HasForeignKey("CrashId")
                        .IsRequired()
                        .HasConstraintName("fk_ou_crash");

                    b.Navigation("Crash");
                });

            modelBuilder.Entity("CrashReport.Models.PedestrianBicyclistDetail", b =>
                {
                    b.HasOne("CrashReport.Models.CrashPerson", "CrashPerson")
                        .WithMany("PedestrianBicyclistDetails")
                        .HasForeignKey("CrashPersonId")
                        .IsRequired()
                        .HasConstraintName("fk_pd_cp");

                    b.Navigation("CrashPerson");
                });

            modelBuilder.Entity("CrashReport.Models.VehicleDamage", b =>
                {
                    b.HasOne("CrashReport.Models.CrashVehicle", "CrashVehicle")
                        .WithMany("VehicleDamages")
                        .HasForeignKey("CrashVehicleId")
                        .IsRequired()
                        .HasConstraintName("fk_vd_crash_vehicle");

                    b.Navigation("CrashVehicle");
                });

            modelBuilder.Entity("CrashReport.Models.Witness", b =>
                {
                    b.HasOne("CrashReport.Models.Crash", "Crash")
                        .WithMany("Witnesses")
                        .HasForeignKey("CrashId")
                        .IsRequired()
                        .HasConstraintName("fk_w_crash");

                    b.Navigation("Crash");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CrashReport.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CrashReport.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrashReport.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CrashReport.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CrashReport.Models.Crash", b =>
                {
                    b.Navigation("ContributoryFactors");

                    b.Navigation("CrashConditions");

                    b.Navigation("CrashLocations");

                    b.Navigation("CrashPeople");

                    b.Navigation("CrashSketches");

                    b.Navigation("CrashVehicles");

                    b.Navigation("CrashWeathers");

                    b.Navigation("DangerousGoods");

                    b.Navigation("OfficialUses");

                    b.Navigation("Witnesses");
                });

            modelBuilder.Entity("CrashReport.Models.CrashPerson", b =>
                {
                    b.Navigation("PedestrianBicyclistDetails");
                });

            modelBuilder.Entity("CrashReport.Models.CrashVehicle", b =>
                {
                    b.Navigation("CrashPeople");

                    b.Navigation("VehicleDamages");
                });

            modelBuilder.Entity("CrashReport.Models.Person", b =>
                {
                    b.Navigation("CrashPeople");

                    b.Navigation("CrashVehicles");

                    b.Navigation("DriversLicences");
                });

            modelBuilder.Entity("CrashReport.Models.Vehicle", b =>
                {
                    b.Navigation("CrashVehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
