// <auto-generated />
using System;
using CrashReport.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrashReport.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CrashReport.Models.ContributoryFactor", b =>
                {
                    b.Property<int>("FactorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FactorId"));

                    b.Property<int>("CrashId")
                        .HasColumnType("int");

                    b.Property<string>("FactorCategory")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FactorDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsMajorFactor")
                        .HasColumnType("bit");

                    b.HasKey("FactorId");

                    b.HasIndex("CrashId");

                    b.HasIndex("FactorCategory");

                    b.ToTable("contributory_factors");
                });

            modelBuilder.Entity("CrashReport.Models.Crash", b =>
                {
                    b.Property<int>("CrashId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrashId"));

                    b.Property<string>("BriefDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CapturingNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CasNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CrNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("CrashDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("CrashTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IncidentReportNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("KmMarker")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte>("NoOfAppendices")
                        .HasColumnType("tinyint");

                    b.Property<byte>("NoOfVehiclesInvolved")
                        .HasColumnType("tinyint");

                    b.Property<string>("ProvinceCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("RoadNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<short?>("SpeedLimitKmh")
                        .HasColumnType("smallint");

                    b.HasKey("CrashId");

                    b.HasIndex("CasNo");

                    b.HasIndex("CrashDate");

                    b.HasIndex("ProvinceCode");

                    b.ToTable("crashes");
                });

            modelBuilder.Entity("CrashReport.Models.CrashCondition", b =>
                {
                    b.Property<int>("ConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConditionId"));

                    b.Property<int>("CrashId")
                        .HasColumnType("int");

                    b.Property<string>("CrashType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("HitAndRun")
                        .HasColumnType("bit");

                    b.Property<string>("LightCondition")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ObstructionType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("OtherObservations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OvertakingControl")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RoadMarkingVisibility")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RoadSegmentGrade")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RoadSignsCondition")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrafficControlType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TyreBurstObserved")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("VehicleLightsCondition")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ConditionId");

                    b.HasIndex("CrashId")
                        .IsUnique();

                    b.ToTable("crash_conditions");
                });

            modelBuilder.Entity("CrashReport.Models.CrashLocation", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("AreaType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BetweenFrom")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BetweenTo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("BuiltUpArea")
                        .HasColumnType("bit");

                    b.Property<string>("CityTown")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompassDirection")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("CrashId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DistanceKm")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("FromPoint")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal?>("GpsXCoordinate")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("GpsYCoordinate")
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("IntersectionRoadNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IntersectionStreet")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("JunctionType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KmMarkerInfo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NextCityTown")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RoadFunctionalClassification")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoadLayout")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RoadSurfaceCondition")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RoadSurfaceQuality")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RoadSurfaceType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StreetRoadName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Suburb")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LocationId");

                    b.HasIndex("CrashId")
                        .IsUnique();

                    b.ToTable("crash_locations");
                });

            modelBuilder.Entity("CrashReport.Models.CrashPerson", b =>
                {
                    b.Property<int>("CrashPersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrashPersonId"));

                    b.Property<string>("AmbulanceServiceRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChildRestraintUsed")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CrashId")
                        .HasColumnType("int");

                    b.Property<int?>("CrashVehicleId")
                        .HasColumnType("int");

                    b.Property<string>("Hospital")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LiquorDrugSuspected")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LiquorDrugTestDone")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte?>("PassengerNumber")
                        .HasColumnType("tinyint");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PersonReference")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SeatbeltHelmetUsed")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SeatingPosition")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SeverityOfInjury")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VehicleReference")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("CrashPersonId");

                    b.HasIndex("CrashId");

                    b.HasIndex("CrashVehicleId");

                    b.HasIndex("PersonId");

                    b.HasIndex("SeverityOfInjury");

                    b.ToTable("crash_persons");
                });

            modelBuilder.Entity("CrashReport.Models.CrashSketch", b =>
                {
                    b.Property<int>("SketchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SketchId"));

                    b.Property<int>("CrashId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NorthDirection")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SketchType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SketchId");

                    b.HasIndex("CrashId");

                    b.ToTable("crash_sketches");
                });

            modelBuilder.Entity("CrashReport.Models.CrashVehicle", b =>
                {
                    b.Property<int>("CrashVehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrashVehicleId"));

                    b.Property<string>("AlcoholSuspected")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AlcoholTestResult")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BreakdownCompany")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CrashId")
                        .HasColumnType("int");

                    b.Property<int?>("DriverPersonId")
                        .HasColumnType("int");

                    b.Property<string>("DrugSuspected")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DrugTestResult")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PassengersForReward")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PositionBeforeCrash")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SeatbeltUsed")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleManoeuvre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VehicleReference")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("CrashVehicleId");

                    b.HasIndex("CrashId");

                    b.HasIndex("DriverPersonId");

                    b.HasIndex("VehicleId");

                    b.ToTable("crash_vehicles");
                });

            modelBuilder.Entity("CrashReport.Models.CrashWeather", b =>
                {
                    b.Property<int>("CrashId")
                        .HasColumnType("int");

                    b.Property<string>("WeatherCondition")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CrashId", "WeatherCondition");

                    b.ToTable("crash_weather");
                });

            modelBuilder.Entity("CrashReport.Models.DangerousGoods", b =>
                {
                    b.Property<int>("DgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DgId"));

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CrashId")
                        .HasColumnType("int");

                    b.Property<string>("EmergencyServicesActivated")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GoodsCarried")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PlacardDisplayed")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SpillageObserved")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UnNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VapourGasEmission")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("VehicleReference")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("DgId");

                    b.HasIndex("CrashId");

                    b.ToTable("dangerous_goods");
                });

            modelBuilder.Entity("CrashReport.Models.DriversLicence", b =>
                {
                    b.Property<int>("LicenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LicenceId"));

                    b.Property<DateOnly?>("DateOfIssue")
                        .HasColumnType("date");

                    b.Property<string>("LicenceCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LicenceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LicenceType")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PrdpCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("LicenceId");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("drivers_licences");
                });

            modelBuilder.Entity("CrashReport.Models.OfficialUse", b =>
                {
                    b.Property<int>("OfficialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfficialId"));

                    b.Property<string>("AccidentRegisterNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CapturingNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("CompletedDate")
                        .HasColumnType("date");

                    b.Property<string>("CompletedInitials")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CompletedRank")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompletedServiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompletedSignature")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CompletedSurname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeOnly?>("CompletedTime")
                        .HasColumnType("time");

                    b.Property<int>("CrashId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DateStamp")
                        .HasColumnType("date");

                    b.Property<string>("DepartmentNameOccurred")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DepartmentNameReported")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InspectedByInitials")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("InspectedByRank")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InspectedByServiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InspectedBySignature")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InspectedBySurname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OccurrenceBookNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OfficeWhereOccurred")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OfficeWhereReported")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SapsCasNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OfficialId");

                    b.HasIndex("CrashId")
                        .IsUnique();

                    b.ToTable("official_use");
                });

            modelBuilder.Entity("CrashReport.Models.PedestrianBicyclistDetail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<string>("ClothingColour")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CrashPersonId")
                        .HasColumnType("int");

                    b.Property<string>("LocationReCrossing")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Manoeuvre")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PedestrianAction")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PositionOnRoad")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("DetailId");

                    b.HasIndex("CrashPersonId")
                        .IsUnique();

                    b.ToTable("pedestrian_bicyclist_details");
                });

            modelBuilder.Entity("CrashReport.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<byte?>("Age")
                        .HasColumnType("tinyint");

                    b.Property<string>("CellPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CountryOfOrigin")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullNames")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HomeAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("IdNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OtherPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PopulationGroup")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WorkContactAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("PersonId");

                    b.HasIndex("IdNumber");

                    b.HasIndex("Surname");

                    b.ToTable("persons");
                });

            modelBuilder.Entity("CrashReport.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Colour")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CountryOfRegistration")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenceDiscNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LicenceTypeFitting")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Make")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrivateOrBusiness")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SpecialFunction")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrailerLicenceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VehicleCategory")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VehicleTypeCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("VinNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VehicleId");

                    b.HasIndex("LicenceDiscNumber");

                    b.HasIndex("VinNumber");

                    b.ToTable("vehicles");
                });

            modelBuilder.Entity("CrashReport.Models.VehicleDamage", b =>
                {
                    b.Property<int>("DamageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DamageId"));

                    b.Property<int>("CrashVehicleId")
                        .HasColumnType("int");

                    b.Property<string>("DamagePoint")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("DamageId");

                    b.HasIndex("CrashVehicleId");

                    b.ToTable("vehicle_damage");
                });

            modelBuilder.Entity("CrashReport.Models.Witness", b =>
                {
                    b.Property<int>("WitnessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WitnessId"));

                    b.Property<string>("CellPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CrashId")
                        .HasColumnType("int");

                    b.Property<string>("IdNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OtherPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SurnameInitials")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WorkContactAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("WitnessId");

                    b.HasIndex("CrashId");

                    b.ToTable("witnesses");
                });

            modelBuilder.Entity("CrashReport.Models.ContributoryFactor", b =>
                {
                    b.HasOne("CrashReport.Models.Crash", "Crash")
                        .WithMany("ContributoryFactors")
                        .HasForeignKey("CrashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crash");
                });

            modelBuilder.Entity("CrashReport.Models.CrashCondition", b =>
                {
                    b.HasOne("CrashReport.Models.Crash", "Crash")
                        .WithOne("CrashCondition")
                        .HasForeignKey("CrashReport.Models.CrashCondition", "CrashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crash");
                });

            modelBuilder.Entity("CrashReport.Models.CrashLocation", b =>
                {
                    b.HasOne("CrashReport.Models.Crash", "Crash")
                        .WithOne("CrashLocation")
                        .HasForeignKey("CrashReport.Models.CrashLocation", "CrashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crash");
                });

            modelBuilder.Entity("CrashReport.Models.CrashPerson", b =>
                {
                    b.HasOne("CrashReport.Models.Crash", "Crash")
                        .WithMany("CrashPersons")
                        .HasForeignKey("CrashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrashReport.Models.CrashVehicle", "CrashVehicle")
                        .WithMany("Passengers")
                        .HasForeignKey("CrashVehicleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CrashReport.Models.Person", "Person")
                        .WithMany("CrashPersons")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Crash");

                    b.Navigation("CrashVehicle");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CrashReport.Models.CrashSketch", b =>
                {
                    b.HasOne("CrashReport.Models.Crash", "Crash")
                        .WithMany("CrashSketches")
                        .HasForeignKey("CrashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crash");
                });

            modelBuilder.Entity("CrashReport.Models.CrashVehicle", b =>
                {
                    b.HasOne("CrashReport.Models.Crash", "Crash")
                        .WithMany("CrashVehicles")
                        .HasForeignKey("CrashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrashReport.Models.Person", "Driver")
                        .WithMany("DrivenVehicles")
                        .HasForeignKey("DriverPersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CrashReport.Models.Vehicle", "Vehicle")
                        .WithMany("CrashVehicles")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crash");

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CrashReport.Models.CrashWeather", b =>
                {
                    b.HasOne("CrashReport.Models.Crash", "Crash")
                        .WithMany("CrashWeathers")
                        .HasForeignKey("CrashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crash");
                });

            modelBuilder.Entity("CrashReport.Models.DangerousGoods", b =>
                {
                    b.HasOne("CrashReport.Models.Crash", "Crash")
                        .WithMany("DangerousGoods")
                        .HasForeignKey("CrashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crash");
                });

            modelBuilder.Entity("CrashReport.Models.DriversLicence", b =>
                {
                    b.HasOne("CrashReport.Models.Person", "Person")
                        .WithOne("DriversLicence")
                        .HasForeignKey("CrashReport.Models.DriversLicence", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CrashReport.Models.OfficialUse", b =>
                {
                    b.HasOne("CrashReport.Models.Crash", "Crash")
                        .WithOne("OfficialUse")
                        .HasForeignKey("CrashReport.Models.OfficialUse", "CrashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crash");
                });

            modelBuilder.Entity("CrashReport.Models.PedestrianBicyclistDetail", b =>
                {
                    b.HasOne("CrashReport.Models.CrashPerson", "CrashPerson")
                        .WithOne("PedestrianBicyclistDetail")
                        .HasForeignKey("CrashReport.Models.PedestrianBicyclistDetail", "CrashPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrashPerson");
                });

            modelBuilder.Entity("CrashReport.Models.VehicleDamage", b =>
                {
                    b.HasOne("CrashReport.Models.CrashVehicle", "CrashVehicle")
                        .WithMany("VehicleDamages")
                        .HasForeignKey("CrashVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrashVehicle");
                });

            modelBuilder.Entity("CrashReport.Models.Witness", b =>
                {
                    b.HasOne("CrashReport.Models.Crash", "Crash")
                        .WithMany("Witnesses")
                        .HasForeignKey("CrashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crash");
                });

            modelBuilder.Entity("CrashReport.Models.Crash", b =>
                {
                    b.Navigation("ContributoryFactors");

                    b.Navigation("CrashCondition");

                    b.Navigation("CrashLocation");

                    b.Navigation("CrashPersons");

                    b.Navigation("CrashSketches");

                    b.Navigation("CrashVehicles");

                    b.Navigation("CrashWeathers");

                    b.Navigation("DangerousGoods");

                    b.Navigation("OfficialUse");

                    b.Navigation("Witnesses");
                });

            modelBuilder.Entity("CrashReport.Models.CrashPerson", b =>
                {
                    b.Navigation("PedestrianBicyclistDetail");
                });

            modelBuilder.Entity("CrashReport.Models.CrashVehicle", b =>
                {
                    b.Navigation("Passengers");

                    b.Navigation("VehicleDamages");
                });

            modelBuilder.Entity("CrashReport.Models.Person", b =>
                {
                    b.Navigation("CrashPersons");

                    b.Navigation("DrivenVehicles");

                    b.Navigation("DriversLicence");
                });

            modelBuilder.Entity("CrashReport.Models.Vehicle", b =>
                {
                    b.Navigation("CrashVehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
